name: pytorch38
channels:
  - bioconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.13.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - captum=0.7.0=0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - cryptography=39.0.1=py38h9ce1e76_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - datrie=0.8.2=py38h497a2fe_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dendropy=4.6.1=pyhdfd78af_0
  - docutils=0.20.1=py38h578d9bd_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipython_genutils=0.2.0=py_1
  - iqtree=1.6.12=he513fc3_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_1
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py38h578d9bd_0
  - jupyter_server=1.24.0=pyhd8ed1ab_0
  - jupyterlab=3.5.0=pyhd8ed1ab_0
  - jupyterlab-fonts=2.1.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.22.0=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mafft=7.505=hec16e2b_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.6=py38h417a72b_1
  - mkl_random=1.2.2=py38h417a72b_1
  - nbclassic=1.0.0=pyh8b2e9e2_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.11.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nextclade=3.18.1=h9ee0642_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.18=hd6dcaed_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pangolin=1.1.14=py_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.1.2=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - prometheus_client=0.18.0=pyhd8ed1ab_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h955ad1f_4
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytools=2020.1=py_0
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py38h0a891b7_4
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - send2trash=1.8.2=pyh41d4057_0
  - seqtk=1.2=0
  - setuptools=67.8.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snakemake-minimal=5.13.0=py_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=pyh41d4057_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - torchaudio=0.12.1=py38_cu113
  - torchvision=0.13.1=py38_cu113
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=1.26.16=py38h06a4308_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.24.1
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - alembic==1.4.1
      - anndata==0.9.1
      - anyio==3.7.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - autopage==0.5.2
      - bio==1.5.9
      - biopython==1.81
      - biothings-client==0.3.0
      - bleach==6.0.0
      - blinker==1.7.0
      - cachetools==5.3.1
      - click==8.1.4
      - clickclick==20.10.2
      - cliff==4.4.0
      - cloudpickle==3.0.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorlog==6.8.0
      - comm==0.1.3
      - connexion==2.7.0
      - contourpy==1.1.0
      - databricks-cli==0.18.0
      - datasets==2.13.0
      - debugpy==1.6.7
      - dill==0.3.6
      - docker==6.1.3
      - evaluate==0.4.0
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - filelock==3.12.2
      - flask==3.0.0
      - flatbuffers==23.5.26
      - fonttools==4.40.0
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - future==0.18.3
      - gast==0.4.0
      - gitpython==3.1.40
      - google-auth==2.20.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - gprofiler-official==1.0.0
      - greenlet==3.0.2
      - grpcio==1.54.2
      - gunicorn==21.2.0
      - h5py==3.9.0
      - hf-xet==1.2.0
      - huggingface-hub==0.15.1
      - imageio==2.33.0
      - importlib==1.0.4
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - inflection==0.5.1
      - ipykernel==6.23.2
      - ipython==8.12.2
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.2
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - joblib==1.2.0
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-path==0.3.2
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.6.3
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-widgets==1.1.7
      - keras==2.11.0
      - lazy-object-proxy==1.9.0
      - libclang==16.0.0
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - lineages==2020-05-19
      - llvmlite==0.40.1
      - mako==1.3.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - mistune==3.0.1
      - mlflow==1.15.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - mygene==3.2.2
      - natsort==8.4.0
      - nbconvert==7.6.0
      - nbformat==5.9.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - nltk==3.8.1
      - notebook==6.5.4
      - numba==0.57.1
      - numpy==1.21.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - openapi-schema-validator==0.6.2
      - openapi-spec-validator==0.7.1
      - opt-einsum==3.3.0
      - optuna==2.7.0
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.2
      - pathable==0.4.3
      - patsy==0.5.3
      - pbr==6.0.0
      - platformdirs==3.7.0
      - plotly==5.18.0
      - pooch==1.7.0
      - prettytable==3.9.0
      - prometheus-client==0.17.0
      - prometheus-flask-exporter==0.23.0
      - prompt-toolkit==3.0.38
      - protobuf==3.19.6
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydeprecate==0.3.2
      - pygments==2.15.1
      - pyjwt==2.8.0
      - pymsaviz==0.4.2
      - pynndescent==0.5.10
      - pyparsing==3.1.0
      - pyperclip==1.8.2
      - pyrsistent==0.19.3
      - python-editor==1.0.4
      - python-json-logger==2.0.7
      - pytorch-lightning==1.6.5
      - pytorch-nlp==0.5.0
      - pytorch-ranger==0.1.1
      - pytz==2023.3
      - pyzmq==25.1.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - querystring-parser==1.2.4
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - safetensors==0.3.1
      - scanpy==1.9.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentencepiece==0.1.99
      - session-info==1.0.0
      - smmap==5.0.1
      - soupsieve==2.4.1
      - sqlalchemy==1.3.23
      - sqlparse==0.4.4
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - stevedore==5.1.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.3.0
      - test-tube==0.7.5
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==1.12.1
      - torch-optimizer==0.3.0
      - torchmetrics==0.9.0
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.30.2
      - triton==3.0.0
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - umap-learn==0.5.3
      - uri-template==1.3.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - websocket-client==1.6.0
      - werkzeug==3.0.1
      - widgetsnbextension==3.6.6
      - wordcloud==1.9.2
      - wrapt==1.15.0
      - xxhash==3.2.0
      - yarl==1.9.2
      - zipp==3.15.0
prefix: /home/audp/anaconda3/envs/pytorch38
